# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdate', models.DateField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('daysno', models.PositiveIntegerField(help_text='Enter the max number of days you will be keeping it for')),
                ('reqdate', models.DateField(blank=True, help_text='Enter the date you will be needing it before the date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('dress_pic', models.FileField(blank=True, null=True, upload_to='images/dresspics/')),
                ('detail', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rentday', models.PositiveIntegerField(blank=True, help_text='Days of rent you would allow')),
            ],
        ),
        migrations.CreateModel(
            name='DressInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Dress.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('dress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Dress')),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('dress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Dress')),
                ('orderuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Order')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('daysno', models.PositiveIntegerField(help_text='Enter the max number of days the user will be keeping it for')),
                ('reqdate', models.DateField(blank=True, help_text='Enter the date the fine limit days start', null=True)),
                ('active', models.BooleanField(default=False)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Dress')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=200, null=True)),
                ('type_pic', models.ImageField(blank=True, null=True, upload_to='images/typepics/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=14)),
                ('location', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dress',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Type'),
        ),
        migrations.AddField(
            model_name='dress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='dress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Dress'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
