# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170725_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
