# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170725_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
