# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_dress_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_pic', models.FileField(blank=True, null=True, upload_to='images/dresspics/')),
            ],
        ),
    ]
