# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_tempimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='search_indexval',
            field=models.FloatField(blank=True, default=9),
        ),
        migrations.AlterField(
            model_name='dress',
            name='search_index',
            field=models.PositiveIntegerField(blank=True, default=9),
        ),
    ]
